### ISSUE TITLE
[인터페이스] 실시간 데이터 플랫폼 연동

### ISSUE THREAD

**Issue by jane1721** [jane1721/e-commerce#16]
### Task

- [x] `return true;` 하는 빈 껍데기 만들어서 주문 성공 시 호출
- [ ] Mock API 만들기
- [ ] Feign client 로 호출 테스트
