### ISSUE TITLE
[레포지토리 초기화] GitHub Repository 설정

### ISSUE THREAD

**Issue by jane1721** [jane1721/e-commerce#4]
### Task
- [ ] Github Repostiory 생성
- [ ] Spring Boot Initial Commit
- [ ] 아키텍처 기반 패키지 설계
- [ ] 서버 Configration 설정 (`application.yml`)
- [ ] 로컬 DB 셋팅 및 연결
