### ISSUE TITLE
[테스트] 단위 테스트 작성

### ISSUE THREAD

**Issue by jane1721** [jane1721/e-commerce#9]
### Task

- [x] 유저 도메인 비즈니스 로직
- [x] 상품 도메인 비즈니스 로직
- [x] 주문 도메인 비즈니스 로직
- [x] 결제 도메인 비즈니스 로직
- [x] 선착순 쿠폰 도메인 비즈니스 로직
